### ISSUE TITLE
no module named 'absl'

### ISSUE THREAD

**Issue by yuqwang913** [dataabc/weiboSpider#251]
为了更好的解决问题，请认真回答下面的问题。等到问题解决，请及时关闭本issue。<br>

- 问：请您指明哪个版本运行出错（github版/PyPi版/全部）？<br>
答：

- 问：您使用的是否是最新的程序（是/否）？<br>
答：

- 问：爬取任意用户都会运行出错吗（是/否）？<br>
答：

- 问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？<br>
答：

- 问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的**user_id**及您配置的**since_date**，方便我们定位出错微博（非必填）？<br>
答：

- 问：如果方便，请您描述出错详情，最好附上错误提示。<br>
答：
git clone之后进入目录，然后执行：

python -m weibo_spider

之后报错：
![image](https://user-images.githubusercontent.com/50217068/97790801-079dea00-1bcc-11eb-9548-86b20fe64a3d.png)

另行安装absl-py后依然无法解决

请问这是怎么回事呢？应该如何解决？

非常感谢

**Comment by dataabc** [comment]
感谢反馈。

可能是absl的安装版本不对，比如你使用的是python3，但是安装的是python2，可以使用
```
$ python -m pip install absl-py
```
安装，如果出错，可以更换absl的版本。

如果还有问题，欢迎继续讨论

**Comment by mingdonglin** [comment]
我也遇到这个问题 原因是absl和lxml依赖C\C++库libxml2, libxslt 所以需要wheel安装 
lxml的whl文件看这个问答
https://stackoverflow.com/questions/40444671/installing-lxml-libxml2-libxslt-for-python-3-5-on-windows-10
absl的whl文件从这里下载
https://pypi.org/project/absl-py/#modal-close
下载好两个whl文件之后安装到你的python 详细步骤看下面这个网址
https://blog.csdn.net/weixin_38501796/article/details/79292935
然后执行源码安装的pip install -r requirements.txt 
出现让你修改config.json的中文就成功了


下面是我自己的过程 重点看加粗的句子
C:\Users\13719\Downloads\absl_py-0.11.0-py3-none-any.whl
C:\Users\13719\Downloads\lxml-4.6.2-cp39-cp39-win_amd64.whl

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> pip3 install lxml
Collecting lxml
  Downloading lxml-4.6.2-cp39-cp39-win_amd64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 59 kB/s
Installing collected packages: lxml
Successfully installed lxml-4.6.2
PS C:\WINDOWS\system32> cd C:\Users\13719\maomao\weiboSpider
PS C:\Users\13719\maomao\weiboSpider> python3 -m weibo_spider
PS C:\Users\13719\maomao\weiboSpider> python -m weibo_spider
Traceback (most recent call last):
  File "C:\Users\13719\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\13719\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\13719\maomao\weiboSpider\weibo_spider\__main__.py", line 4, in <module>
    from absl import app
**ModuleNotFoundError: No module named 'absl'**
PS C:\Users\13719\maomao\weiboSpider> pip install -r requirements.txt
Requirement already satisfied: requests==2.23.0 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (2.23.0)
Requirement already satisfied: tqdm==4.46.1 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (4.46.1)
Collecting absl-py==0.9.0
  Using cached absl-py-0.9.0.tar.gz (104 kB)
Requirement already satisfied: six in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from absl-py==0.9.0->-r requirements.txt (line 4)) (1.15.0)
Collecting lxml==4.5.1
  Using cached lxml-4.5.1.tar.gz (4.5 MB)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from requests==2.23.0->-r requirements.txt (line 2)) (3.0.4)
**Using legacy 'setup.py install' for absl-py, since package 'wheel' is not installed.
Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.**
Installing collected packages: lxml, absl-py
  Attempting uninstall: lxml
    Found existing installation: lxml 4.6.2
    Uninstalling lxml-4.6.2:
      Successfully uninstalled lxml-4.6.2
    Running setup.py install for lxml ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\13719\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\13719\\AppData\\Local\\Temp\\pip-install-dzjtuvht\\lxml_6ea1dca0bd9e43ef81e11e8d9688e1f1\\setup.py'"'"'; __file__='"'"'C:\\Users\\13719\\AppData\\Local\\Temp\\pip-install-dzjtuvht\\lxml_6ea1dca0bd9e43ef81e11e8d9688e1f1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\13719\AppData\Local\Temp\pip-record-8utnpr6z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\13719\appdata\local\programs\python\python39\Include\lxml'
         cwd: C:\Users\13719\AppData\Local\Temp\pip-install-dzjtuvht\lxml_6ea1dca0bd9e43ef81e11e8d9688e1f1\
    Complete output (94 lines):
    Building lxml version 4.5.1.
    Building without Cython.
    Building against pre-built libxml2 andl libxslt libraries
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\lxml
    copying src\lxml\builder.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\cssselect.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\sax.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\_elementpath.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\__init__.py -> build\lib.win-amd64-3.9\lxml
    creating build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win-amd64-3.9\lxml\html
    creating build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\etree.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\etree_api.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\__init__.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\src
    creating build\temp.win-amd64-3.9\Release\src\lxml
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc\lxml\includes -Ic:\users\13719\appdata\local\programs\python\python39\include -Ic:\users\13719\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc\lxml\etree.c /Fobuild\temp.win-amd64-3.9\Release\src\lxml\etree.obj -w
    cl: 命令行 warning D9025 :正在重写“/W3”(用“/w”)
    etree.c
    C:\Users\13719\AppData\Local\Temp\pip-install-dzjtuvht\lxml_6ea1dca0bd9e43ef81e11e8d9688e1f1\src\lxml\includes/etree_defs.h(14): fatal error C1083: 无法打开包括文件: “libxml/xmlversion.h”: No such file or directory
    Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    creating Users
    creating Users\13719
    creating Users\13719\AppData
    creating Users\13719\AppData\Local
    creating Users\13719\AppData\Local\Temp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\13719\AppData\Local\Temp\xmlXPathInitq413xx4c.c /FoUsers\13719\AppData\Local\Temp\xmlXPathInitq413xx4c.obj
    xmlXPathInitq413xx4c.c
    C:\Users\13719\AppData\Local\Temp\xmlXPathInitq413xx4c.c(1): fatal error C1083: 无法打开包括文件: “libxml/xpath.h”: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    *********************************************************************************
    **Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?**
    *********************************************************************************
    ----------------------------------------
  Rolling back uninstall of lxml
  Moving to c:\users\13719\appdata\local\programs\python\python39\lib\site-packages\lxml-4.6.2.dist-info\
   from C:\Users\13719\AppData\Local\Programs\Python\Python39\Lib\site-packages\~xml-4.6.2.dist-info
  Moving to c:\users\13719\appdata\local\programs\python\python39\lib\site-packages\lxml\
   from C:\Users\13719\AppData\Local\Programs\Python\Python39\Lib\site-packages\~xml
ERROR: Command errored out with exit status 1: 'c:\users\13719\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\13719\\AppData\\Local\\Temp\\pip-install-dzjtuvht\\lxml_6ea1dca0bd9e43ef81e11e8d9688e1f1\\setup.py'"'"'; __file__='"'"'C:\\Users\\13719\\AppData\\Local\\Temp\\pip-install-dzjtuvht\\lxml_6ea1dca0bd9e43ef81e11e8d9688e1f1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\13719\AppData\Local\Temp\pip-record-8utnpr6z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\13719\appdata\local\programs\python\python39\Include\lxml' Check the logs for full command output.
PS C:\Users\13719\maomao\weiboSpider> pip install -r requirements.txt
Requirement already satisfied: lxml==4.6.2 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (4.6.2)
Requirement already satisfied: requests==2.23.0 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (2.23.0)
Requirement already satisfied: tqdm==4.46.1 in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (4.46.1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/absl-py/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/absl-py/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/absl-py/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/absl-py/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/absl-py/
ERROR: Could not find a version that satisfies the requirement absl-py==0.11.0
ERROR: No matching distribution found for absl-py==0.11.0
PS C:\Users\13719\maomao\weiboSpider> python3 -m weibo_spide
PS C:\Users\13719\maomao\weiboSpider>
PS C:\Users\13719\maomao\weiboSpider>
PS **C:\Users\13719\maomao\weiboSpider>**
PS C:\Users\13719\maomao\weiboSpider> cd C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts
PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts> pip3 install wheel
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/wheel/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/wheel/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/wheel/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/wheel/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/wheel/
ERROR: Could not find a version that satisfies the requirement wheel
ERROR: No matching distribution found for wheel
PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts>
**PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts> pip install wheel**
Collecting wheel
  Downloading wheel-0.36.1-py2.py3-none-any.whl (34 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.1
**PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts> pip install C:\Users\13719\Downloads\absl_py-0.11.0-py3-none-any.whl**
Processing c:\users\13719\downloads\absl_py-0.11.0-py3-none-any.whl
Requirement already satisfied: six in c:\users\13719\appdata\local\programs\python\python39\lib\site-packages (from absl-py==0.11.0) (1.15.0)
Installing collected packages: absl-py
Successfully installed absl-py-0.11.0
PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts> pip install C:\Users\13719\Downloads\lxml-4.6.2-cp39-cp39-win_amd64.whl
Processing c:\users\13719\downloads\lxml-4.6.2-cp39-cp39-win_amd64.whl
lxml is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts> pip --force-reinstall C:\Users\13719\Downloads\lxml-4.6.2-cp39-cp39-win_amd64.whl

Usage:
  pip <command> [options]

no such option: --force-reinstall
PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts> pip -force-reinstall C:\Users\13719\Downloads\lxml-4.6.2-cp39-cp39-win_amd64.whl

Usage:
  pip <command> [options]

no such option: -f
**PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts> pip install --force-reinstall C:\Users\13719\Downloads\lxml-4.6.2-cp39-cp39-win_amd64.whl**
Processing c:\users\13719\downloads\lxml-4.6.2-cp39-cp39-win_amd64.whl
Installing collected packages: lxml
  Attempting uninstall: lxml
    Found existing installation: lxml 4.6.2
    Uninstalling lxml-4.6.2:
      Successfully uninstalled lxml-4.6.2
Successfully installed lxml-4.6.2
PS C:\Users\13719\AppData\Local\Programs\Python\Python39\Scripts>
